__version__ = "0.3.0"

from .switch_by_number import NODE_CLASS_MAPPINGS as SWITCH_NODE_CLASS_MAPPINGS
from .switch_by_number import NODE_DISPLAY_NAME_MAPPINGS as SWITCH_NODE_DISPLAY_NAME_MAPPINGS
from .number_condition_checker import NODE_CLASS_MAPPINGS as CONDITION_NODE_CLASS_MAPPINGS
from .number_condition_checker import NODE_DISPLAY_NAME_MAPPINGS as CONDITION_NODE_DISPLAY_NAME_MAPPINGS
from .boolean_index_adder import NODE_CLASS_MAPPINGS as BOOLEAN_NODE_CLASS_MAPPINGS
from .boolean_index_adder import NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_NODE_DISPLAY_NAME_MAPPINGS
from .number_range_index import NODE_CLASS_MAPPINGS as RANGE_NODE_CLASS_MAPPINGS
from .number_range_index import NODE_DISPLAY_NAME_MAPPINGS as RANGE_NODE_DISPLAY_NAME_MAPPINGS
from .string_concatenator import NODE_CLASS_MAPPINGS as CONCAT_NODE_CLASS_MAPPINGS
from .string_concatenator import NODE_DISPLAY_NAME_MAPPINGS as CONCAT_NODE_DISPLAY_NAME_MAPPINGS
from .number_sequence_generator import NODE_CLASS_MAPPINGS as SEQUENCE_NODE_CLASS_MAPPINGS
from .number_sequence_generator import NODE_DISPLAY_NAME_MAPPINGS as SEQUENCE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **SWITCH_NODE_CLASS_MAPPINGS,
    **CONDITION_NODE_CLASS_MAPPINGS,
    **BOOLEAN_NODE_CLASS_MAPPINGS,
    **RANGE_NODE_CLASS_MAPPINGS,
    **CONCAT_NODE_CLASS_MAPPINGS,
    **SEQUENCE_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SWITCH_NODE_DISPLAY_NAME_MAPPINGS,
    **CONDITION_NODE_DISPLAY_NAME_MAPPINGS,
    **BOOLEAN_NODE_DISPLAY_NAME_MAPPINGS,
    **RANGE_NODE_DISPLAY_NAME_MAPPINGS,
    **CONCAT_NODE_DISPLAY_NAME_MAPPINGS,
    **SEQUENCE_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
